"""add_cascade_delete_to_audience_relationships

Revision ID: 0a6ff755ea3d
Revises: 40b0fab2eb29
Create Date: 2025-03-15 01:11:57.299022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6ff755ea3d'
down_revision: Union[str, None] = '40b0fab2eb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audience_subreddits_subreddit_name_fkey', 'audience_subreddits', type_='foreignkey')
    op.create_foreign_key(None, 'audience_subreddits', 'subreddits', ['subreddit_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audience_subreddits', type_='foreignkey')
    op.create_foreign_key('audience_subreddits_subreddit_name_fkey', 'audience_subreddits', 'subreddits', ['subreddit_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###
