"""add cascade delete to foreign keys

Revision ID: 40b0fab2eb29
Revises: fix_post_count_column
Create Date: 2025-03-15 01:05:36.633961

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40b0fab2eb29'
down_revision: Union[str, None] = 'fix_post_count_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audience_subreddits_audience_id_fkey', 'audience_subreddits', type_='foreignkey')
    op.drop_constraint('fk_audience_subreddits_subreddit', 'audience_subreddits', type_='foreignkey')
    op.create_foreign_key(None, 'audience_subreddits', 'subreddits', ['subreddit_name'], ['name'], ondelete='CASCADE')
    op.drop_column('audience_subreddits', 'created_at')
    op.drop_column('audience_subreddits', 'updated_at')
    op.alter_column('audiences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audiences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_audiences_id', table_name='audiences')
    op.create_index(op.f('ix_audiences_name'), 'audiences', ['name'], unique=False)
    op.drop_column('audiences', 'post_count')
    op.alter_column('redditpost', 'subreddit_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subreddits', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subreddits', 'subscribers',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('theme', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('theme_audience_id_fkey', 'theme', type_='foreignkey')
    op.create_foreign_key(None, 'theme', 'audiences', ['audience_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('themepost_theme_id_fkey', 'themepost', type_='foreignkey')
    op.drop_constraint('themepost_post_id_fkey', 'themepost', type_='foreignkey')
    op.create_foreign_key(None, 'themepost', 'redditpost', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'themepost', 'theme', ['theme_id'], ['id'], ondelete='CASCADE')
    op.alter_column('themequestion', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('themequestion_theme_id_fkey', 'themequestion', type_='foreignkey')
    op.create_foreign_key(None, 'themequestion', 'theme', ['theme_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themequestion', type_='foreignkey')
    op.create_foreign_key('themequestion_theme_id_fkey', 'themequestion', 'theme', ['theme_id'], ['id'])
    op.alter_column('themequestion', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'themepost', type_='foreignkey')
    op.drop_constraint(None, 'themepost', type_='foreignkey')
    op.create_foreign_key('themepost_post_id_fkey', 'themepost', 'redditpost', ['post_id'], ['id'])
    op.create_foreign_key('themepost_theme_id_fkey', 'themepost', 'theme', ['theme_id'], ['id'])
    op.drop_constraint(None, 'theme', type_='foreignkey')
    op.create_foreign_key('theme_audience_id_fkey', 'theme', 'audiences', ['audience_id'], ['id'])
    op.alter_column('theme', 'audience_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subreddits', 'subscribers',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subreddits', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('redditpost', 'subreddit_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('audiences', sa.Column('post_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audiences_name'), table_name='audiences')
    op.create_index('ix_audiences_id', 'audiences', ['id'], unique=False)
    op.alter_column('audiences', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('audiences', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('audience_subreddits', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('audience_subreddits', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audience_subreddits', type_='foreignkey')
    op.create_foreign_key('fk_audience_subreddits_subreddit', 'audience_subreddits', 'subreddits', ['subreddit_name'], ['name'], ondelete='CASCADE')
    op.create_foreign_key('audience_subreddits_audience_id_fkey', 'audience_subreddits', 'audiences', ['audience_id'], ['id'])
    # ### end Alembic commands ###
