"""make theme question answer and last_recalculated_at optional

Revision ID: 68d16e518e8c
Revises: 3df60bc2636f
Create Date: 2025-03-12 22:11:31.224607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d16e518e8c'
down_revision: Union[str, None] = '3df60bc2636f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themequestion', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('themequestion', 'last_recalculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themequestion', 'last_recalculated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('themequestion', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
