"""add_audience_timeframe_and_post_limit

Revision ID: 70caa5326087
Revises: 8e5b6a4b5e2b
Create Date: 2025-03-12 11:08:24.111236

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70caa5326087'
down_revision: Union[str, None] = '8e5b6a4b5e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiences', sa.Column('timeframe', sa.String(), nullable=False, server_default='week'))
    op.add_column('audiences', sa.Column('posts_per_subreddit', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('subreddits', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('subreddits', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    # Set default value for null subscribers
    op.execute("UPDATE subreddits SET subscribers = 0 WHERE subscribers IS NULL")
    op.alter_column('subreddits', 'subscribers',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    op.drop_column('subreddits', 'active_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('subreddits', 'subscribers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subreddits', 'updated_at')
    op.drop_column('subreddits', 'created_at')
    op.drop_column('audiences', 'posts_per_subreddit')
    op.drop_column('audiences', 'timeframe')
    # ### end Alembic commands ###
