"""Add themes and posts tables

Revision ID: 8e5b6a4b5e2b
Revises: bfb426a42108
Create Date: 2025-03-12 09:48:39.622554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5b6a4b5e2b'
down_revision: Union[str, None] = 'bfb426a42108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddits', 'icon_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('icon_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
