"""add icon_url to subreddit

Revision ID: bfb426a42108
Revises: df38fae5cacb
Create Date: 2025-03-11 23:40:00.638374

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bfb426a42108'
down_revision: Union[str, None] = 'df38fae5cacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('icon_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddits', 'icon_url')
    # ### end Alembic commands ###
