"""remove subreddit_names from audiences

Revision ID: remove_subreddit_names_from_audiences
Revises: 70caa5326087
Create Date: 2025-03-14 12:45:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'remove_subreddit_names_from_audiences'
down_revision: Union[str, None] = '70caa5326087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiences', 'subreddit_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiences', sa.Column('subreddit_names', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ### 